---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/component: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: agent
              protocol: TCP
              containerPort: 50000
          volumeMounts:
            - name: jenkins
              mountPath: /tmp/jenkins
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
      volumes:
        - name: jenkins
          emptyDir: {}
            
