---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: devops
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/component: devops
spec:
  storageClassName: jenkins-home
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
